name: Docker Image CI

on:
  push:
 #  branches: [ "1master" ]
    branches: [ "master" ]
  pull_request:
 #   branches: [ "1master" ]
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/386, linux/arm/v7, linux/arm/v6, linux/ppc64le
          build-args: |
            DEBIAN_VERSION=${{ matrix.DEBIAN_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: "simonmcnair/mstar-yihack"
          labels: ${{ steps.meta.outputs.labels }}


#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
